<a href="https://colab.research.google.com/github/kartoone/cosc470s24/blob/main/examplecode/softmax2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!git clone https://github.com/kartoone/DeepLearningPython nn
%cd nn

Cloning into 'nn'...
remote: Enumerating objects: 66, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 66 (delta 3), reused 5 (delta 1), pack-reused 55
Receiving objects: 100% (66/66), 16.44 MiB | 18.02 MiB/s, done.
Resolving deltas: 100% (30/30), done.
/content/nn


In [ ]:
from network2 import Network, CrossEntropyCost
import mnist_loader
import numpy as np
training_data, validation_data, test_data = mnist_loader.load_data_wrapper()
training_data = list(training_data)
test_data = list(test_data)[0:3]
net = Network([784, 30, 10])
#print(np.shape(net.biases))
#print(net.biases)
#print(np.shape(test_data))

In [ ]:
net = Network([784, 30, 10], cost=CrossEntropyCost)
net.large_weight_initializer()
net.SGD(training_data, 30, 10, 0.5, evaluation_data=test_data, monitor_evaluation_accuracy=True)

Epoch 0 training complete
[array([2.27143449e-05, 4.77482235e-05, 2.80099404e-03, 7.54458969e-03,
       1.23332043e-05, 1.36032730e-04, 2.09639489e-08, 9.98603189e-01,
       6.87210296e-07, 1.25132873e-03])]
[[2.24801103e-05]
 [4.72558348e-05]
 [2.77210967e-03]
 [7.46678846e-03]
 [1.22060219e-05]
 [1.34629935e-04]
 [2.07477647e-08]
 [9.88305404e-01]
 [6.80123654e-07]
 [1.23842479e-03]]
0.9999999999999999
[array([3.23663003e-04, 2.35927612e-02, 8.13732994e-01, 1.10632950e-02,
       2.67581301e-08, 2.01624255e-03, 1.41624817e-02, 7.06784973e-05,
       4.12314644e-03, 2.85527248e-06])]
[[3.72416774e-04]
 [2.71465689e-02]
 [9.36306633e-01]
 [1.27297732e-02]
 [3.07887414e-08]
 [2.31995174e-03]
 [1.62957944e-02]
 [8.13248895e-05]
 [4.74422125e-03]
 [3.28536581e-06]]
1.0
[array([3.56076421e-07, 9.98677968e-01, 5.25763508e-04, 1.53073225e-03,
       3.81473629e-06, 1.36762129e-03, 4.15897433e-03, 7.49827505e-03,
       1.28013964e-04, 5.49951193e-04])]
[[3.51007359e-07]
 [9.84460905e-01]
 

([],
 [3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3],
 [],
 [])